### ISSUE TITLE
Use sub-apps

### ISSUE THREAD

**Issue by redfish0** [ericferon/glpi-dataflows#6]
Hello,
I created in archisw a child app and cannot select it as a source or destination app in dataflows, is it by design ?

Thanks

Patrick

**Comment by ericferon** [comment]
Yes.Only level 1 items are selected. Best regards,Eric 


Envoyé depuis mon smartphone Samsung Galaxy.
-------- Message d'origine --------De : redfish0 <notifications@github.com> Date : 11/09/18  10:25  (GMT+01:00) À : ericferon/glpi-dataflows <glpi-dataflows@noreply.github.com> Cc : Subscribed <subscribed@noreply.github.com> Objet : [ericferon/glpi-dataflows] Use sub-apps (#6) 
Hello,

I created in archisw a child app and cannot select it as a source or destination app in dataflows, is it by design ?
Thanks
Patrick

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/ericferon/glpi-dataflows","title":"ericferon/glpi-dataflows","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/ericferon/glpi-dataflows"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Use sub-apps (#6)"}],"action":{"name":"View Issue","url":"https://github.com/ericferon/glpi-dataflows/issues/6"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/ericferon/glpi-dataflows/issues/6",
"url": "https://github.com/ericferon/glpi-dataflows/issues/6",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Use sub-apps (#6)",
"sections": [
{
"text": "",
"activityTitle": "**redfish0**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@redfish0",
"facts": [
{
"name": "Repository: ",
"value": "ericferon/glpi-dataflows"
},
{
"name": "Issue #: ",
"value": 6
}
]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"ericferon/glpi-dataflows\",\n\"issueId\": 6,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"ericferon/glpi-dataflows\",\n\"issueId\": 6\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/ericferon/glpi-dataflows/issues/6"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 378228802\n}"
}
],
"themeColor": "26292E"
}
]
